major improvements to untar

diff --git a/bin/untar b/bin/untar
--- a/bin/untar
+++ b/bin/untar
@@ -1,40 +1,75 @@
 #!/bin/bash
 
-(( $# != 1 )) && echo "Usage: $(basename $0) FILENAME" && exit 1
+set -e
+
+# ----------------------------------------------------------- Parse Command Line
+
+if (( $# != 1 )) || [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
+    cat <<EOF
+
+    Usage: $(basename $0) FILENAME
+
+EOF
+
+    exit 0
+fi
 
 FILE="$1"
+[ ! -f "$FILE" ] && echo "Could not find file '$FILE', Aborting." 1>&2 && exit 1
 
-[ ! -f "$FILE" ] && echo "Could not find file '$FILE', Aborting." && exit 1
+# -------------------------------------------------------------------- Execution
 
-EXTENSION="$(echo "$FILE" | awk -F . '{if (NF>1) { print $NF }}')"
-CMP="cat"
 
-case $EXTENSION in
-    gz)
-        gunzip -dc $FILE | tar -xf -
-	;;
-    bz2)
-	bunzip2 -dc $FILE | tar -xf -
-	;;
-    tgz)
-	gunzip -dc $FILE | tar -xf -
-	;;
-    xz)
-	xz -dc $FILE | tar -xf -
-	;;
-    tar)
-	cat $FILE | tar -xf -
-	;;
-    *)
-	echo "Unknown extension: '$EXTENSION', aborting" 1>&2 && exit 1
-	;;
-esac
+if   [[ "$FILE" == *.tar.gz ]] || [[ "$FILE" == *.tgz ]] ; then
+    gunzip -dc "$FILE" | tar -xf -
+elif [[ "$FILE" == *.tar.bz2 ]] ; then
+    bunzip2 -dc "$FILE" | tar -xf -
+elif [[ "$FILE" == *.tar.xz ]] ; then
+    xz -dc "$FILE" | tar -xf -
+elif [[ "$FILE" == *.7z ]] ; then
+    7za x "$FILE"
+elif [[ "$FILE" == *.tar ]] ; then
+    cat "$FILE" | tar -xf -
+else
+    echo "Unknown file type: $FILE" 1>&2
+    exit 1
+fi
 
-#[ "$EXTENSION" = "gz" ] && CMP="gunzip -dc"
-#[ "$EXTENSION" = "bz2" ] && CMP="bunzip2 -dc"
-#$CMP "$FILE" | tar -xf -
+exit 0
 
-exit $?
+    
+# EXTENSION="$(echo "$FILE" | awk -F . '{if (NF>1) { print $NF }}')"
+# CMP="cat"
+
+# case $EXTENSION in
+#     gz)
+#         gunzip -dc "$FILE" | tar -xf -
+# 	;;
+#     bz2)
+# 	bunzip2 -dc "$FILE" | tar -xf -
+# 	;;
+#     tgz)
+# 	gunzip -dc "$FILE" | tar -xf -
+# 	;;
+#     xz)
+# 	xz -dc "$FILE" | tar -xf -
+# 	;;
+#     tar)
+# 	cat "$FILE" | tar -xf -
+# 	;;
+#     7z)
+#         7za x "$FILE"
+#         ;;
+#     *)
+# 	echo "Unknown extension: '$EXTENSION', aborting" 1>&2 && exit 1
+# 	;;
+# esac
+
+# #[ "$EXTENSION" = "gz" ] && CMP="gunzip -dc"
+# #[ "$EXTENSION" = "bz2" ] && CMP="bunzip2 -dc"
+# #$CMP "$FILE" | tar -xf -
+
+# exit $?
 
 
 
